
name: tests

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'



# concurrency:
#   group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
#   cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    # strategy:
    #   matrix:
    #     pip: [yes, no]
    #     os: [osx-64, linux-64]
    #     include:
    #       - os: macos-latest
    #         label: osx-64

    #       - os: ubuntu-latest
    #         label: linux-64

    # name: ${{ matrix.label }}-pip-${{ matrix.pip }}
    # runs-on: ${{ matrix.os }}
    # steps:
    # - run: echo ${{ matrix.os }}-${{ matrix.pip }}-${{ matrix.label }}
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - label: cat-label
            animal: cat
          - label: dog-label
            animal: dog
          # - fruit: banana
          # - fruit: banana
          #   animal: cat
    runs-on: ubuntu-latest
    name: ${{ matrix.fruit }}-${{ matrix.animal }}-${{ matrix.color }}-${{ matrix.label }}
    steps:
    - run: echo ${{ matrix.fruit }}-${{ matrix.animal }}-${{ matrix.color }}