name: reds


on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'
  workflow_dispatch:
  workflow_call:


defaults:
  run:
    shell: bash -l {0}
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      id: clone

    - run: blah
      continue-on-error: true
      id: will-fail
    
    - run: echo "this ran"
      if: steps.will-fail.outcome == 'failure'
      