name: reds2


on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'
  workflow_dispatch:
  workflow_call:


defaults:
  run:
    shell: bash -l {0}



jobs:
  build:
    uses: .github/workflows/test.yml