
name: tests

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'



concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    strategy:
      matrix:
        pip: [yes, no]
        include:
          - os: macos-latest
            label: osx-64
            prefix: /Users/runner/miniconda3/envs/tardis

          - os: ubuntu-latest
            label: linux-64
            prefix: /usr/share/miniconda3/envs/tardis

    name: ${{ matrix.label }}-pip-${{ matrix.pip }}
    runs-on: ${{ matrix.os }}
    steps:
    - run: echo ${{ matrix.os }}-${{ matrix.pip }}-${{ matrix.label }}