name: reds2


on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'
  workflow_dispatch:
  workflow_call:


defaults:
  run:
    shell: bash -l {0}



jobs:
  build:
    if: github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/test.yml
  blah:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{ github.event_name }}